version: '3'
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    network_mode: "host"
    environment:
      TZ: "America/Chicago"
      WEBPASSWORD: "yourpassword"
      DNSMASQ_LISTENING: "all"
      PIHOLE_DNS_: "8.8.8.8;8.8.4.4"
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
